# Generated by Django 5.0.1 on 2024-01-18 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_url', models.CharField(max_length=200)),
                ('domain_added', models.DateTimeField(verbose_name='date added')),
            ],
        ),
    ]
